"""README generator service."""

from __future__ import annotations

from app.db import get_connection
from app.utils.path_utils import out_dir
from app.utils.time_utils import now_iso


def _write_file(filename: str, content: str) -> str:
    out_dir().mkdir(parents=True, exist_ok=True)
    path = out_dir() / filename
    path.write_text(content, encoding="utf-8")
    return str(path)


def _insert_history(doc_type: str, output_path: str) -> None:
    with get_connection() as conn:
        conn.execute(
            """
            INSERT INTO readme_history (type, created_at, output_path)
            VALUES (?, ?, ?)
            """,
            (doc_type, now_iso(), output_path),
        )
        conn.commit()


def generate_profile(data: dict) -> dict:
    content = f"""# {data['name']}

## About
{data['bio']}

## Tech Stack
{data.get('tech') or 'Add your favorite tools and languages.'}

## Links
{data.get('links') or 'Add links to your portfolio, GitHub, or socials.'}

---
Generated by Dragon Dev Companion Desktop.
"""
    path = _write_file("README_PROFILE.md", content)
    _insert_history("profile", path)
    return {"path": path}


def generate_project(data: dict) -> dict:
    content = f"""# {data['title']}

## Description
{data['description']}

## Features
{data.get('features') or '- Feature one\\n- Feature two'}

## Usage
{data.get('usage') or 'Add setup and usage steps here.'}

## Tech Stack
{data.get('stack') or 'List frameworks, languages, and tools.'}

## Links
{data.get('links') or 'Add docs or repo links.'}

---
Generated by Dragon Dev Companion Desktop.
"""
    path = _write_file("README_PROJECT.md", content)
    _insert_history("project", path)
    return {"path": path}


def history() -> list[dict]:
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT * FROM readme_history ORDER BY created_at DESC"
        ).fetchall()
    return [dict(row) for row in rows]
